config/routes.rb
Rails.application.routes.draw do

  root to: "cocktails#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  mount_uploader :photo, PhotoUploader

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true

  validates :cocktail, uniqueness: { scope: :ingredient }
  # for one ingredient there is only a cocktail
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save
    redirect_to cocktails_path
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private
  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail_id = @cocktail.id
    if @dose.save
      redirect_to cocktail_path(@cocktail.id)
    else
      render :new
    end
  end

  private
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cocktails/_form.html.erb
<p> <strong>From=> </strong> views cocktails _form.html.erb </p>

<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Criar o novo registro" %>
<% end %>

app/views/cocktails/destroy.html.erb
<h2><%= @cocktail.name %></h2>

app/views/cocktails/index.html.erb
<p> From index.html.erb </p>

<% @cocktails.each do |cocktail| %>
  <h2><%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
<% end %>
<%= link_to "Crie um novo registro", new_cocktail_path, class: "btn btn-primary" %>

<!-- app/views/pages/home.html.erb -->
<%= cl_image_tag("sample.jpg", :angle =>315,
      width: 200, height: 150, crop: :fill) %>

app/views/cocktails/new.html.erb
<p> From new.html.erb <p>
<%= render "form"%>

app/views/cocktails/show.html.erb
<p> <strong>From=> </strong> show.html.erb </p>
<h2><%= @cocktail.name %></h2>

<p><% @cocktail.doses.each do |d| %>
  <p> Descrição: <%= d.description %> - <%= d.ingredient.name %> </p>
<% end %>

<%= cl_image_tag @cocktail.photo, height: 230, width: 200, crop: :fill %></p>

<%= link_to "Delete esse registro", cocktail_path(@cocktail), method: :delete, class: "btn btn-primary" %>
<%= link_to "Volte para a lista de registros", cocktails_path, class: "btn btn-primary" %>


<%= link_to "Insira um atributo", new_cocktail_dose_path(@cocktail.id), class: "btn btn-primary" %>

app/views/doses/new.html.erb
<p> <strong>From=> </strong> views doses new.html.erb </p>

<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.error_notification %>
  <%= f.input :description %>
  <%= f.association :ingredient %>

  <%= f.submit "Crie um novo atributo" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Added by me for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- app/views/pages/home.html.erb -->
<%= cl_image_tag("THE_IMAGE_ID_FROM_LIBRARY",
      width: 400, height: 300, crop: :fill) %>

<!-- for face detection -->
<%= cl_image_tag("IMAGE_WITH_FACE_ID",
      width: 400, height: 300, crop: :thumb, gravity: :face) %>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>

  <%= simple_form_for(@product) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit %>
<% end %>

  <!-- <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div> -->
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= cl_image_tag @product.photo, height: 300, width: 400, crop: :fill %>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>